<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Carregado DENTRO do programa do usuário (DOTNET_STARTUP_HOOKS) para registrar onde ele
    parou com um erro. net8.0 para funcionar em programas .NET 8 ou mais novos.
  -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

</Project>
